//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("proiect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13th_Floor_Elevators___You_re_Gonna_Miss_Me {
            get {
                object obj = ResourceManager.GetObject("13th Floor Elevators - You\'re Gonna Miss Me", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13th_Floor_Elevators___You_re_Gonna_Miss_Me1 {
            get {
                object obj = ResourceManager.GetObject("13th Floor Elevators - You\'re Gonna Miss Me1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _790 {
            get {
                object obj = ResourceManager.GetObject("790", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap America___Rainy_Day {
            get {
                object obj = ResourceManager.GetObject("America - Rainy Day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap America___Rainy_Day1 {
            get {
                object obj = ResourceManager.GetObject("America - Rainy Day1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bad_Brains___Sailin__On {
            get {
                object obj = ResourceManager.GetObject("Bad Brains - Sailin\' On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bauhaus___St__Vitus_Dance {
            get {
                object obj = ResourceManager.GetObject("Bauhaus - St. Vitus Dance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Big_Black___Kerosene {
            get {
                object obj = ResourceManager.GetObject("Big Black - Kerosene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_Flag___Beat_My_Head_Against_the_Wall {
            get {
                object obj = ResourceManager.GetObject("Black Flag - Beat My Head Against the Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Black_Sabbath__Solitude {
            get {
                object obj = ResourceManager.GetObject("Black Sabbath -Solitude", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blondie___Heart_of_Glass {
            get {
                object obj = ResourceManager.GetObject("Blondie - Heart of Glass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Oyster_Cult___Astronomy {
            get {
                object obj = ResourceManager.GetObject("Blue Oyster Cult - Astronomy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Can___Future_Days {
            get {
                object obj = ResourceManager.GetObject("Can - Future Days", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comus___Diana {
            get {
                object obj = ResourceManager.GetObject("Comus - Diana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cream___Sunshine_Of_Your_Love {
            get {
                object obj = ResourceManager.GetObject("Cream - Sunshine Of Your Love", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cream___Sunshine_Of_Your_Love1 {
            get {
                object obj = ResourceManager.GetObject("Cream - Sunshine Of Your Love1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap David_Bowie___Oh__You_pretty_things {
            get {
                object obj = ResourceManager.GetObject("David Bowie - Oh! You pretty things", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap David_Bowie___Speed_of_Life {
            get {
                object obj = ResourceManager.GetObject("David Bowie - Speed of Life", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap David_Bowie__Scary_Monsters__And_Super_Creeps_ {
            get {
                object obj = ResourceManager.GetObject("David Bowie -Scary Monsters (And Super Creeps)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dead_Kennedys___Trust_Your_Mechanic {
            get {
                object obj = ResourceManager.GetObject("Dead Kennedys - Trust Your Mechanic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Design_fără_titlu__1_ {
            get {
                object obj = ResourceManager.GetObject("Design fără titlu (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Devo___Uncontrollable_Urge {
            get {
                object obj = ResourceManager.GetObject("Devo - Uncontrollable Urge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dinosaur_Jr___Sludgefeast {
            get {
                object obj = ResourceManager.GetObject("Dinosaur Jr - Sludgefeast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eno___I_ll_Come_Running {
            get {
                object obj = ResourceManager.GetObject("Eno - I\'ll Come Running", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frank_Zappa___Peaches_En_Regalia {
            get {
                object obj = ResourceManager.GetObject("Frank Zappa - Peaches En Regalia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gang_of_Four___Damaged_Goods {
            get {
                object obj = ResourceManager.GetObject("Gang of Four - Damaged Goods", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gentle_Giant___Proclamation {
            get {
                object obj = ResourceManager.GetObject("Gentle Giant - Proclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Herbie_Hancock___Hidden_Shadows {
            get {
                object obj = ResourceManager.GetObject("Herbie Hancock - Hidden Shadows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hüsker_Dü___Something_I_Learned_Today {
            get {
                object obj = ResourceManager.GetObject("Hüsker Dü - Something I Learned Today", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jefferson_Airplane___Today {
            get {
                object obj = ResourceManager.GetObject("Jefferson Airplane - Today", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jefferson_Airplane___Today1 {
            get {
                object obj = ResourceManager.GetObject("Jefferson Airplane - Today1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jethro_Tull___Aqualung {
            get {
                object obj = ResourceManager.GetObject("Jethro Tull - Aqualung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Joy_Division___A_Means_to_an_End {
            get {
                object obj = ResourceManager.GetObject("Joy Division - A Means to an End", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Joy_Division___Disorder {
            get {
                object obj = ResourceManager.GetObject("Joy Division - Disorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap King_Crimson___21st_Century_Schizoid_Man {
            get {
                object obj = ResourceManager.GetObject("King Crimson - 21st Century Schizoid Man", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap King_Crimson___21st_Century_Schizoid_Man1 {
            get {
                object obj = ResourceManager.GetObject("King Crimson - 21st Century Schizoid Man1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap King_Crimson___Matte_kudasai {
            get {
                object obj = ResourceManager.GetObject("King Crimson - Matte kudasai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kraftwerk___Das_Model {
            get {
                object obj = ResourceManager.GetObject("Kraftwerk - Das Model", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Led_Zeppelin___Dazed_and_Confused {
            get {
                object obj = ResourceManager.GetObject("Led Zeppelin - Dazed and Confused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Led_Zeppelin___Dazed_and_Confused1 {
            get {
                object obj = ResourceManager.GetObject("Led Zeppelin - Dazed and Confused1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Leonard_Cohen___Master_Song {
            get {
                object obj = ResourceManager.GetObject("Leonard Cohen - Master Song", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lou_Reed___Perfect_Day {
            get {
                object obj = ResourceManager.GetObject("Lou Reed - Perfect Day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Love___Andmoreagain {
            get {
                object obj = ResourceManager.GetObject("Love - Andmoreagain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Love___Andmoreagain1 {
            get {
                object obj = ResourceManager.GetObject("Love - Andmoreagain1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lynyrd_Skynyrd___Free_Bird {
            get {
                object obj = ResourceManager.GetObject("Lynyrd Skynyrd - Free Bird", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__2_ {
            get {
                object obj = ResourceManager.GetObject("melodinator (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__3_ {
            get {
                object obj = ResourceManager.GetObject("melodinator (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__4_ {
            get {
                object obj = ResourceManager.GetObject("melodinator (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__4_1 {
            get {
                object obj = ResourceManager.GetObject("melodinator (4)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__4_2 {
            get {
                object obj = ResourceManager.GetObject("melodinator (4)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__5_ {
            get {
                object obj = ResourceManager.GetObject("melodinator (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__6_ {
            get {
                object obj = ResourceManager.GetObject("melodinator (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__7_ {
            get {
                object obj = ResourceManager.GetObject("melodinator (7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__7_1 {
            get {
                object obj = ResourceManager.GetObject("melodinator (7)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__8_ {
            get {
                object obj = ResourceManager.GetObject("melodinator (8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__9_ {
            get {
                object obj = ResourceManager.GetObject("melodinator (9)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator__9_1 {
            get {
                object obj = ResourceManager.GetObject("melodinator (9)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap melodinator_1 {
            get {
                object obj = ResourceManager.GetObject("melodinator_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Miles_Davis___Shhh__Peaceful {
            get {
                object obj = ResourceManager.GetObject("Miles Davis - Shhh  Peaceful", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mingus___Solo_Dancer__Stop__Look__And_Listen__Sinner_Jim_Whitney {
            get {
                object obj = ResourceManager.GetObject("Mingus - Solo Dancer, Stop! Look! And Listen, Sinner Jim Whitney", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minutemen___Anxious_Mo_Fo {
            get {
                object obj = ResourceManager.GetObject("Minutemen - Anxious Mo-Fo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mort_Garson___Symphony_for_a_Spider_Plant {
            get {
                object obj = ResourceManager.GetObject("Mort Garson - Symphony for a Spider Plant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Muddy_Waters___Mean_Disposition {
            get {
                object obj = ResourceManager.GetObject("Muddy Waters - Mean Disposition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nick_Drake___Place_to_Be {
            get {
                object obj = ResourceManager.GetObject("Nick Drake - Place to Be", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Patti_Smith___Gloria {
            get {
                object obj = ResourceManager.GetObject("Patti Smith - Gloria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paul_McCartney___Wings___Jet {
            get {
                object obj = ResourceManager.GetObject("Paul McCartney & Wings - Jet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pink_Floyd___Interstellar_Overdrive {
            get {
                object obj = ResourceManager.GetObject("Pink Floyd - Interstellar Overdrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pink_Floyd___Interstellar_Overdrive1 {
            get {
                object obj = ResourceManager.GetObject("Pink Floyd - Interstellar Overdrive1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pink_Floyd__Dogs {
            get {
                object obj = ResourceManager.GetObject("Pink Floyd- Dogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pixies___Debaser {
            get {
                object obj = ResourceManager.GetObject("Pixies - Debaser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rush___Limelight {
            get {
                object obj = ResourceManager.GetObject("Rush - Limelight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap send {
            get {
                object obj = ResourceManager.GetObject("send", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Silver_Apples___Lovefingers {
            get {
                object obj = ResourceManager.GetObject("Silver Apples - Lovefingers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Silver_Apples___Lovefingers1 {
            get {
                object obj = ResourceManager.GetObject("Silver Apples - Lovefingers1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Siouxsie_and_The_Banshees___Spellbound {
            get {
                object obj = ResourceManager.GetObject("Siouxsie and The Banshees - Spellbound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Small_Faces___Song_of_a_Baker {
            get {
                object obj = ResourceManager.GetObject("Small Faces - Song of a Baker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Small_Faces___Song_of_a_Baker1 {
            get {
                object obj = ResourceManager.GetObject("Small Faces - Song of a Baker1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sonic_Youth___Teen_Age_Riot {
            get {
                object obj = ResourceManager.GetObject("Sonic Youth - Teen Age Riot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sparks___Thank_God_It_s_Not_Christmas {
            get {
                object obj = ResourceManager.GetObject("Sparks - Thank God It\'s Not Christmas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steely_Dan___Do_It_Again {
            get {
                object obj = ResourceManager.GetObject("Steely Dan - Do It Again", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T__Rex___Cosmic_Dancer {
            get {
                object obj = ResourceManager.GetObject("T. Rex - Cosmic Dancer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Talking_Heads___Born_Under_Punches {
            get {
                object obj = ResourceManager.GetObject("Talking Heads - Born Under Punches", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Television___Marquee_Moon {
            get {
                object obj = ResourceManager.GetObject("Television - Marquee Moon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Beach_Boys____God_only_knows {
            get {
                object obj = ResourceManager.GetObject("The Beach Boys -  God only knows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Beach_Boys____God_only_knows1 {
            get {
                object obj = ResourceManager.GetObject("The Beach Boys -  God only knows1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Beatles___Eleanor_Rigby {
            get {
                object obj = ResourceManager.GetObject("The Beatles - Eleanor Rigby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Beatles___Eleanor_Rigby1 {
            get {
                object obj = ResourceManager.GetObject("The Beatles - Eleanor Rigby1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Byrds___Renaissance_Fair {
            get {
                object obj = ResourceManager.GetObject("The Byrds - Renaissance Fair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Byrds___Renaissance_Fair1 {
            get {
                object obj = ResourceManager.GetObject("The Byrds - Renaissance Fair1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Clash___The_Guns_of_Brixton {
            get {
                object obj = ResourceManager.GetObject("The Clash - The Guns of Brixton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Cure___Disintegration {
            get {
                object obj = ResourceManager.GetObject("The Cure - Disintegration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_doors___End_of_the_Night {
            get {
                object obj = ResourceManager.GetObject("The doors - End of the Night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_doors___End_of_the_Night1 {
            get {
                object obj = ResourceManager.GetObject("The doors - End of the Night1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap the_Jimi_Hendrix_Experience___1983 {
            get {
                object obj = ResourceManager.GetObject("the Jimi Hendrix Experience - 1983", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap the_Jimi_Hendrix_Experience___19831 {
            get {
                object obj = ResourceManager.GetObject("the Jimi Hendrix Experience - 19831", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Kinks___Do_you_remember_Walter {
            get {
                object obj = ResourceManager.GetObject("The Kinks - Do you remember Walter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Kinks___Do_you_remember_Walter1 {
            get {
                object obj = ResourceManager.GetObject("The Kinks - Do you remember Walter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Kinks___Lola {
            get {
                object obj = ResourceManager.GetObject("The Kinks - Lola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Modern_Lovers___Astral_Plane {
            get {
                object obj = ResourceManager.GetObject("The Modern Lovers - Astral Plane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Monkees___The_Door_Into_Summer {
            get {
                object obj = ResourceManager.GetObject("The Monkees - The Door Into Summer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Monkees___The_Door_Into_Summer1 {
            get {
                object obj = ResourceManager.GetObject("The Monkees - The Door Into Summer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_pretty_things___S_F__Sorrow_is_born {
            get {
                object obj = ResourceManager.GetObject("The pretty things - S.F. Sorrow is born", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_pretty_things___S_F1 {
            get {
                object obj = ResourceManager.GetObject("The pretty things - S.F1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Smiths___I_Know_It_s_Over {
            get {
                object obj = ResourceManager.GetObject("The Smiths - I Know It\'s Over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Sound___I_can_t_escape_myself {
            get {
                object obj = ResourceManager.GetObject("The Sound - I can\'t escape myself", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Stooges___Down_on_the_Street {
            get {
                object obj = ResourceManager.GetObject("The Stooges - Down on the Street", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Velvet_Underground___Heroin {
            get {
                object obj = ResourceManager.GetObject("The Velvet Underground - Heroin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_West_Coast_Pop_Art_Experimental_Band___Shifting_Sands {
            get {
                object obj = ResourceManager.GetObject("The West Coast Pop Art Experimental Band - Shifting Sands", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_West_Coast_Pop_Art_Experimental_Band___Shifting_Sands1 {
            get {
                object obj = ResourceManager.GetObject("The West Coast Pop Art Experimental Band - Shifting Sands1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Zombies___Care_of_Cell_44 {
            get {
                object obj = ResourceManager.GetObject("The Zombies - Care of Cell 44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap The_Zombies___Care_of_Cell_441 {
            get {
                object obj = ResourceManager.GetObject("The Zombies - Care of Cell 441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap This_Heat___Paper_Hats {
            get {
                object obj = ResourceManager.GetObject("This Heat - Paper Hats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ty {
            get {
                object obj = ResourceManager.GetObject("ty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ultimate_Spinach___Jazz_Thing {
            get {
                object obj = ResourceManager.GetObject("Ultimate Spinach - Jazz Thing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ultimate_Spinach___Jazz_Thing1 {
            get {
                object obj = ResourceManager.GetObject("Ultimate Spinach - Jazz Thing1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_design {
            get {
                object obj = ResourceManager.GetObject("Untitled design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_design1 {
            get {
                object obj = ResourceManager.GetObject("Untitled design1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Van_der_Graaf_Generator___Killer {
            get {
                object obj = ResourceManager.GetObject("Van der Graaf Generator - Killer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video {
            get {
                object obj = ResourceManager.GetObject("video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Weather_Report___Black_market {
            get {
                object obj = ResourceManager.GetObject("Weather Report - Black market", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap White_Noise___Your_Hidden_Dreams {
            get {
                object obj = ResourceManager.GetObject("White Noise - Your Hidden Dreams", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap White_Noise___Your_Hidden_Dreams1 {
            get {
                object obj = ResourceManager.GetObject("White Noise - Your Hidden Dreams1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wire___Mannequin {
            get {
                object obj = ResourceManager.GetObject("Wire - Mannequin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XTC___When_You_re_Near_Me_I_Have_Difficulty {
            get {
                object obj = ResourceManager.GetObject("XTC - When You\'re Near Me I Have Difficulty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yes___Close_to_the_edge {
            get {
                object obj = ResourceManager.GetObject("Yes - Close to the edge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YouTube_Emblem {
            get {
                object obj = ResourceManager.GetObject("YouTube-Emblem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
